app/components/AddToCartButton.jsx
app/components/Category.jsx
app/components/FlipClock.jsx
app/components/Header.jsx
app/components/Like.jsx
app/components/LoadMore.jsx
app/components/ProductCard.jsx
app/components/Sales.jsx
app/components/SectionTitle.jsx
app/not-found.jsx

Make category and sales section dynamic

Make category and sales section dynamic

---

app/affiliate/page.jsx
app/career/page.jsx
app/components/MainNav.jsx
app/components/MiniNav.jsx
app/components/Sales.jsx
app/discount/page.jsx
app/layout.js
app/login/page.jsx
app/merchant/page.jsx
app/partner/page.jsx
app/registration/page.jsx
public/css/common.css
public/css/flash-sale.css
public/css/login.css
public/css/responsive.css

login registration , top  navmenu page create and sum css isseu fixed

login registration , top  navmenu page create and sum css isseu fixed

---

app/components/FlipClock.jsx
app/components/Header.jsx
app/components/MainNav.jsx
package-lock.json
package.json
public/css/header.css

Make header sticky and fix flipclock

Make header sticky and fix flipclock

---

app/components/FlipClock.jsx
app/components/Header.jsx
app/components/HoverMenu.jsx
app/components/Sales.jsx
app/components/SectionTitle.jsx
app/hooks/useCountdown.js
app/hooks/useScreenSize.js
app/login/page.jsx
app/registration/page.jsx
package-lock.json
package.json
public/css/login.css

Fix flipclock and header

---

app/components/Header.jsx

Fix window not defiened issue

---

app/components/HoverMenu.jsx
app/components/MainNav.jsx
app/components/SectionTitle.jsx

Fix hover menu

---

app/components/SectionTitle.jsx
app/hooks/useScreenSize.js

Fix resize issue

---

app/components/CategoryHoverMenu.jsx
app/components/Header.jsx
app/components/MobileNav.jsx

Fix mobile responsive navigation

Fix mobile responsive navigation

---

app/components/SocialLink.jsx
app/components/productDetail/Breadcrumb.jsx
app/components/productDetail/ProductDeliveryDetail.jsx
app/components/productDetail/ProductImage.jsx
app/components/productDetail/ProductInformetion.jsx
app/components/productDetail/ProductLeftSide.jsx
app/components/productDetail/ProductLongDescription.jsx
app/components/productDetail/ProductRightSide.jsx
app/components/productDetail/ProductSlider.jsx
app/components/productDetail/SimilerProduct.jsx
app/components/productDetail/SimilerProductItems.jsx
app/hooks/useScreenSize.js
app/product/page.jsx
public/css/product-details.css

product details page React Components create

product details page React components create

---

app/components/SectionTitle.jsx
app/product/page.jsx

Add recent view component inside product page

---

app/components/productDetail/ProductImage.jsx
app/components/productDetail/ProductLeftSide.jsx
app/components/productDetail/ProductSlider.jsx

Fix product details page slider

Fix product details page slider

---

app/components/productDetail/ProductSlider.jsx
public/css/product-details.css
public/css/responsive.css

product slider css issue fixed

product slider css issue fixed

---

app/components/Sales.jsx
app/components/SectionTitle.jsx
app/components/productDetail/SimilerProduct.jsx
app/layout.js
app/product/page.jsx
public/css/product-details.css
public/css/responsive.css

Fix product details page responsive issue

Fix product details page responsive issue

---

app/components/MobileNav.jsx

Fix search popup hide issue

---

app/components/productCategory/CategoryVariant.jsx

Fix category

---

app/components/AddToCartButton.jsx
app/components/productCategory/CategoryLeftSide.jsx
app/components/productCategory/CategoryProductArchive.jsx
app/components/productCategory/CategoryProductArchiveItems.jsx
app/components/productCategory/CategoryRightSide.jsx
app/components/productCategory/FindLooking.jsx
app/components/productCategory/Pagination.jsx
app/components/productCategory/PriceRange.jsx
app/components/productCategory/ShotBy.jsx
app/components/productCategory/StarRating.jsx
app/components/productCategory/StarRatingItems.jsx
app/components/productCategory/SubCategoryList.jsx
package-lock.json
package.json
public/css/product-category.css

Category page Right side all component create and React-range-slider-input Create

Category page Right side all component create

---

app/components/productCategory/PriceRange.jsx
app/layout.js
app/page.js

Fix price range slider value and district modal issue.

Fix price range slider value and district modal issue

---

app/components/productCategory/CategoryColorVariant.jsx
app/components/productCategory/CategoryLeftSide.jsx
app/components/productCategory/CategoryProductArchive.jsx
app/components/productCategory/CategoryProductArchiveItems.jsx
app/components/productCategory/CategoryRightSide.jsx
app/components/productCategory/CategoryVariant.jsx
app/components/productCategory/ViewMoreLink.jsx
app/components/productDetail/ProductDeliveryDetail.jsx
app/components/viewAllProduct/ViewAllBanner.jsx
app/components/viewAllProduct/ViewAllCategories.jsx
app/components/viewAllProduct/ViewAllCategoryItems.jsx
app/components/viewAllProduct/ViewAllCategoryTitle.jsx
app/components/viewAllProduct/ViewAllProduct.jsx
app/components/viewAllProduct/ViewAllProductItems.jsx
app/viewall/page.jsx
app/viewallproduct/page.jsx
public/css/product-category.css
public/css/product-details.css

View more component done And View all page component Create

View more component done And View all page component Create

---

app/components/Sales.jsx

Fix flipclock and flash sale

---

app/components/Sales.jsx
app/components/viewAllProduct/ViewAllProductItems.jsx
app/viewall/page.jsx
app/viewallproduct/page.jsx
public/css/flash-sale.css

Recent View ,add to cart and Wish Component added

Recent View

---

app/category/page.js
app/components/ProductCategoryItem.jsx

Fix category page

---

app/components/MainSlider.jsx
app/components/MainSliderItems.jsx
app/services/getHomeBrand.js
app/services/getHomeCategory.js
app/services/getHomeSlider.js
public/css/hero-banner.css
public/css/responsive.css

home slider issue fixed

---

app/components/MainSliderItems.jsx

home page conditionally slider content show hide

home page conditionally slider content show hide

---

app/components/MainSlider.jsx
app/components/MainSliderItems.jsx
app/components/PartnerItems.jsx
app/components/ProductCategories.jsx

Slider Iamge Path Issue fixed

---

app/components/MainSliderItems.jsx

Fix home slider minor issue

---

app/components/Category.jsx
app/components/CategoryMainMenuList.jsx
app/components/HeroSlider.jsx
app/services/getCategoryMenu.js
app/services/getHomeCategory.js
app/utils.js

Fix category menu with backend logic.

Fix category menu with backend logic.

---

app/components/CategoryMainMenuList.jsx
public/css/flash-sale.css

css button padding change and length 1 to 0 change

css change

---

app/components/CategoryHoverMenu.jsx
app/components/HeroSlider.jsx

Fix category manu with max 10 item limit

Fix category manu with max 10 item limit

---

app/components/Category.jsx
app/components/SectionTitle.jsx
app/components/viewAllProduct/ViewAllCategoryItems.jsx
app/viewall/page.jsx

Make view all page dynamic

---

app/viewall/page.jsx

Fix category all view

---

app/api/auth/[...nextauth]/route.js
app/components/MainSliderItems.jsx
app/components/viewAllProduct/ViewAllBanner.jsx
app/components/viewAllProduct/ViewAllCategories.jsx
app/layout.js
app/loading.jsx
app/login/page.jsx
public/css/animatloading.css
public/css/hero-banner.css

animate loadin html css add

---

app/api/auth/[...nextauth]/route.js
app/components/MainNav.jsx
app/components/SigninBtn.jsx
app/components/SignoutBtn.jsx
app/login/page.jsx

Fix login and logout issue

---

app/components/ProductCategoryItem.jsx
app/loading.jsx

category & brand title limit

---

app/components/ProductCard.jsx
app/components/Sales.jsx
app/services/getFlashSaleProduct.js
public/css/flash-sale.css

flas sale api connect

---

app/components/JustForYou.jsx

update for_you_products variable

update for_you_products variable

---

app/components/JustForYou.jsx
app/components/viewAllProduct/ViewAllBanner.jsx
app/components/viewAllProduct/ViewAllProduct.jsx
app/components/viewAllProduct/ViewAllProductItems.jsx
app/viewallproduct/page.jsx
public/css/flash-sale.css

view all link click then just for product show in other page

view all link click then just for product show in other page

---

app/viewallproduct/page.jsx

Fix view all page banner image

Fix view all page banner image

---

app/components/SectionTitle.jsx
app/viewall/page.jsx

view all page banner image issue fixed

view all page banner image issue fixed

---

app/components/Sales.jsx
app/components/viewAllProduct/ViewAllProductItems.jsx
app/viewallproduct/page.jsx

flash sale view all page work

---

app/api/auth/[...nextauth]/route.js
app/login/page.jsx
app/services/getLoginToken.js

Add credential login

---

app/api/auth/[...nextauth]/route.js

Fix next auth secret

---

app/api/auth/[...nextauth]/route.js

Fix auth in production

---

app/components/ProductCard.jsx
app/components/ProductCategories.jsx
app/components/productCategory/CategoryProductArchiveItems.jsx
app/components/productCategory/CategoryRightSide.jsx
public/css/product-category.css
public/css/product-details.css

category page some issue fixed

category page some issue fixed

---

app/components/CategoryMainMenuList.jsx
app/components/HeroSlider.jsx

slider left category menu issue fixed

slider left category menu issue fixed

---

app/components/ProductCard.jsx
app/components/ProductCategoryItem.jsx
app/components/Sales.jsx
app/components/viewAllProduct/ViewAllCategoryTitle.jsx
app/utils.js

flash & just for product title truncate

flash & just for product title truncate

---

app/components/Category.jsx
app/components/ProductCategoryItem.jsx
app/services/getHomePageBodyBrand.js
public/css/common.css

Category home page body API create and implementation

Category home page body API create and implementation

---

app/components/ProductSearchResult.jsx
app/components/ProductSearchResultMobile.jsx
public/css/header.css

Header Search title alignment issue fixed

Header Search title alignment issue fixed

---

app/components/Sales.jsx

flash sale length issue fixed

---

app/components/MainNav.jsx

updated selected division

---

app/components/Sales.jsx
app/components/viewAllProduct/ViewAllCategoryTitle.jsx
app/components/viewAllProduct/ViewAllProductItems.jsx
app/services/getFlashSaleProduct.js
app/services/getJustForYouProduct.js
app/viewall/page.jsx
app/viewallproduct/page.jsx

flash sale End time Api work

---

app/components/MainNav.jsx
app/services/getFlashSaleProduct.js
app/services/getJustForYouProduct.js
app/viewallproduct/page.jsx

header search modal in outside modal

header seacr modal in outside modal

---

app/components/MainNav.jsx
app/components/ProductSearchResult.jsx
app/components/ProductSearchResultMobile.jsx
app/viewallproduct/page.jsx

search product link dynamic

---

app/components/MainNav.jsx
app/components/viewAllProduct/ViewAllProduct.jsx
app/components/viewAllProduct/ViewAllProductItems.jsx
app/viewall/page.jsx
app/viewallproduct/page.jsx

view all page data checked

---

app/components/MainNav.jsx

updated out side click

---

app/category/[slug]/page.jsx
app/components/productCategory/CategoryColorVariant.jsx
app/components/productCategory/CategoryColorVariantItems.jsx
app/components/productCategory/CategoryLeftSide.jsx
app/components/productCategory/CategoryVariant.jsx
app/components/productCategory/CategoryVariantItems.jsx
app/services/getCategorydetailBySlug.js

Fix category page filter without range switcher

Fix category page filter without range switcher

---

app/category/[slug]/page.jsx
app/components/ProductCard.jsx
app/components/productCategory/CategoryProductArchive.jsx
app/components/productCategory/CategoryProductArchiveItems.jsx
app/components/productCategory/CategoryRightSide.jsx
app/components/viewAllProduct/ViewAllProduct.jsx
app/components/viewAllProduct/ViewAllProductItems.jsx
app/viewallproduct/page.jsx
public/css/flash-sale.css
public/css/header.css

category page and some css issue

category page and some css issue

---

app/components/Sales.jsx

flash sale setting change

---

app/components/CategoryHoverMenu.jsx
app/components/MainNav.jsx
app/components/ProductSearchResult.jsx
app/components/ProductSearchResultMobile.jsx
app/services/getCategoryMenu.js

category hover menu and search modal

category hover menu and search modal

---

app/components/ProductSearchResult.jsx
app/components/ProductSearchResultMobile.jsx

updated use client

---

app/components/ProductSearchResult.jsx
app/components/ProductSearchResultMobile.jsx

useEffect import code

---

app/components/MainNav.jsx
app/components/ProductSearchResult.jsx
app/components/ProductSearchResultMobile.jsx

location search

---

app/(customerdashboard)/dashboard/page.jsx
app/components/SignoutBtn.jsx
app/login/page.jsx
app/services/getOrdersByUserId.js

order History API work Done

---

app/components/MainNav.jsx

user is logged in Register link hidden

user is logged in Register link hidden

---

app/components/MainNav.jsx
public/css/responsive.css

updated code

---

app/components/MainNav.jsx
app/components/ProductSearchResult.jsx

header search

---

app/components/MainNav.jsx
app/components/ProductSearchResultMobile.jsx

product searc

---

app/components/customerDashboard/CustomerLeftSideNavbar.jsx

href issue fixed

---

app/(customerdashboard)/dashboard/page.jsx

import issue

---

app/category/[slug]/page.jsx
app/components/productCategory/CategoryLeftSide.jsx
app/components/productCategory/SubCategoryList.jsx

sub category menu list show in category page

sub category menu list show in category page

---

app/components/productCategory/PriceRange.jsx

string to int value

---

app/category/[slug]/page.jsx
app/components/productCategory/CategoryPagination.jsx
app/components/productCategory/CategoryRightSide.jsx
app/components/productCategory/Pagination.jsx
public/css/product-category.css

category page pagination work done

category page pagination work done

---

app/components/ordersummary/OrderProductItems.jsx
app/components/ordersummary/OrderShippingAddress.jsx
app/components/ordersummary/OrderSummaryLeft.jsx
app/components/ordersummary/OrderSummaryRight.jsx
app/components/ordersummary/ProductOrderPriceSummary.jsx
app/orderinvoice/page.jsx
app/thankyou/page.jsx
public/css/order-invoice.css

thank you page dynamic

---

app/google-profile/page.jsx

google profile page design

---

app/components/orderinvoice/InvoiceFooter.jsx
app/components/orderinvoice/InvoicePaymentHistory.jsx
app/components/orderinvoice/InvoiceProductDetail.jsx
app/components/orderinvoice/OrderInvoiceTop.jsx
app/orderinvoice/page.jsx

invoice page component create and API same data show

invoice page component create and Api same data show

---

public/css/product-details.css

product detail page top space remove

product detail page top space remove

---

app/category/[slug]/page.jsx
app/components/ProductCategoryItem.jsx
app/components/orderinvoice/InvoiceProductDetail.jsx
app/components/productCategory/CategoryProductArchiveItems.jsx
app/components/productCategory/ShotBy.jsx
app/services/getCategorydetailBySlug.js

invoice page and category slug page

invoice page and category slug page

---

app/registration/page.jsx

Login with 12 digit

---

app/(customerdashboard)/orderhistory/loading.jsx
app/components/customerDashboard/orderhistory/CustomerRightsids.jsx
app/components/orderview/OrderViewAmmount.jsx
app/components/orderview/OrderViewDetail.jsx
app/components/orderview/OrderViewPaymentHistory.jsx
app/components/orderview/OrderViewSummary.jsx
app/components/orderview/OrderViewTimeLine.jsx
app/components/orderview/OrderViewTopBtn.jsx
app/layout.js
app/orderview/loading.jsx
app/orderview/page.jsx
public/css/orderview.css

Order View Page design and component added

Order View Page design and component added

---

app/components/DistrictList.jsx
app/orderinvoice/page.jsx

set district id in local Storage

set district id in localstorage

---

app/components/customerDashboard/CustomerLeftSideNavbar.jsx
app/components/customerDashboard/manageProfile/ManageProfileItem.jsx/ManageBasicInfo.jsx
app/orderinvoice/page.jsx
app/thankyou/page.jsx

invoice and thank you page district id change

invoice and thank you page district id change

---

app/paynow/page.jsx
public/css/common.css
public/css/paynow.css

pay now page work done

---

app/(customerdashboard)/manage-profile/loading.jsx
app/components/customerDashboard/manageProfile/ManageProfile.jsx
app/components/customerDashboard/manageProfile/ManageProfileItem.jsx/ManageBasicInfo.jsx
app/services/postManageBasicInfo.js

basic info

---

app/components/ProductCard.jsx
app/components/customerDashboard/manageProfile/ManageProfile.jsx
app/components/customerDashboard/manageProfile/ManageProfileItem.jsx/ManageBasicInfo.jsx
app/components/customerDashboard/manageProfile/ManageProfileItem.jsx/ManageIDVerification.jsx
app/components/customerDashboard/manageProfile/ManageProfileItem.jsx/ManageNomineeInfo.jsx
app/services/postManageIdVerificationInfo.js
app/services/postManageNomineeInfo.js

manage  id veriverification

---

app/components/ProductCard.jsx

productcart single type check

---

app/components/ProductCard.jsx
app/components/customerDashboard/manageProfile/ManageProfileItem.jsx/ManageIDVerification.jsx
app/components/customerDashboard/manageProfile/ManageProfileItem.jsx/ManageShippingAddress.jsx
app/components/customerDashboard/manageProfile/ManageProfileItem.jsx/ManageTakePhoto.jsx
app/components/viewAllProduct/ViewAllProductItems.jsx
app/services/getProfilePicture.js
app/services/postManageProfilePicture.js

take a photo

---

app/components/Sales.jsx

flash sale arrows setting

---

app/components/MainNav.jsx

default location show

---

app/components/Header.jsx
app/components/orderview/OrderViewPaymentHistory.jsx
app/components/orderview/OrderViewSummary.jsx
app/components/orderview/OrderViewTopBtn.jsx
app/components/orderview/OrderViewWrapp.jsx
app/services/getOrderPaymentHistory.js

order payment history done

---

app/components/productCategory/CategoryProductArchiveItems.jsx
app/orderinvoice/page.jsx

window print for invoice page change

window print for invoice page change

---

app/components/productCategory/CategoryProductArchiveItems.jsx

category details page pric change

category details page pric change

---

app/components/Category.jsx
app/components/Sales.jsx
app/components/productDetail/ProductDeliveryDetail.jsx
app/components/productDetail/ProductDiscussion.jsx
app/components/viewAllProduct/ViewAllCategoryTitle.jsx
app/components/viewAllProduct/ViewAllFlashCheck.jsx
app/page.js
app/utils.js
app/viewall/page.jsx
app/viewallproduct/page.jsx
public/css/common.css
public/css/flash-sale.css

home page flash sales and viewall page recent vaiew product setting done

home page flash sales and viewall page recent vaiew product setting done

---

app/api/auth/[...nextauth]/route.js
app/cart-page/CartPageInfo.jsx
app/components/Header.jsx
app/components/JustForYou.jsx
app/components/Like.jsx
app/components/ProductCard.jsx
app/components/SocialLink.jsx
app/components/paynow/PayNowPaymentOption.jsx
app/components/productDetail/ProductDeliveryDetail.jsx
app/components/productDetail/ProductDiscussion.jsx
app/components/productDetail/ProductInformetion.jsx
app/components/viewAllProduct/ViewAllFlashCheck.jsx
app/components/viewAllProduct/ViewAllProduct.jsx
app/login/page.jsx
app/new-user/page.jsx
app/products/[slug]/ProductDetails.jsx
app/products/[slug]/page.jsx
app/registration/page.jsx
app/services/deleteSelectedProduct.js
app/services/getAllAuthUserLocation.js
app/services/getDeleteCartProduct.js
app/services/getRecentViewProduct.js
app/services/getShowAddToCartProduct.js
app/shipping-page/buy-now/BuyNowShippingProductPage.jsx
app/viewallproduct/page.jsx
public/css/flash-sale.css

console log remove

---

app/components/viewAllProduct/ViewAllFlashCheck.jsx
app/viewallproduct/page.jsx

length issue

---

app/viewallproduct/page.jsx

useSearchperam added in viewall page

useSearchperam added in viewall page

---

app/(customerdashboard)/(settings)/customershippingaddress/page.jsx
app/(customerdashboard)/(settings)/passwordtxnotp/page.jsx
app/components/customerDashboard/CustomerLeftSideNavbar.jsx
app/components/customerDashboard/settings/customershipping/CustomerShippingRightInfo.jsx
app/components/customerDashboard/settings/passwordtxnotp/ChangePasswordForm.jsx
app/components/customerDashboard/settings/passwordtxnotp/ChangeTransactionOtp.jsx
app/components/customerDashboard/settings/passwordtxnotp/PasswordTopNav.jsx
app/components/customerDashboard/settings/passwordtxnotp/PasswordTxnOtpRight.jsx
app/components/orderview/OrderViewAmmount.jsx
app/components/orderview/OrderViewWrapp.jsx
app/layout.js
app/services/postManagePassword.js
public/css/customer-password-setting.css
public/js/custom.js

customer change page work

---

public/css/common.css

end time css change

---

app/cart-page/CartPageInfo.jsx
app/shipping-page/cart-product/AddToCartProductShippingPage.jsx

cart page loading change

---

app/cart-page/CartPageInfo.jsx
app/shipping-page/buy-now/BuyNowShippingProductPage.jsx
app/shipping-page/cart-product/AddToCartProductShippingPage.jsx
public/css/shipping-details.css

cart page design update

---

app/components/customerDashboard/affiliate/affiliatemyteam/MyTeamList.jsx
app/components/customerDashboard/manageProfile/ManageProfileItem.jsx/ManageBasicInfo.jsx
app/components/productDetail/ProductDiscussion.jsx
app/shipping-page/cart-product/AddToCartProductShippingPage.jsx

updated branch

---

app/cart-page/CartPageInfo.jsx
app/components/productCategory/Pagination.jsx
app/components/productDetail/SimilerProductItems.jsx
app/new-user/page.jsx

console.log hide

---

app/(customerdashboard)/(affiliate)/affiliateteam/[userId]/page.jsx
app/components/customerDashboard/affiliate/affiliatemyteam/MyTeamList.jsx
app/components/customerDashboard/affiliate/affiliatemyteam/SearchMyTeam.jsx
app/services/affiliate/getAffiliateMembersTeam.js

Team member list show and search functionality

Team member list show and search functionality

---

app/(customerdashboard)/(affiliate)/affiliateteam/[userId]/page.jsx
app/components/customerDashboard/affiliate/affiliatemyteam/AffiliateTeamWrapp.jsx
app/services/affiliate/getAffiliateMembersTeam.js
app/services/affiliate/getAffiliateTeam.js

affiliate team page pagination

affiliate team page pagination

---

app/(customerdashboard)/(affiliate)/affiliateteam/[userId]/page.jsx
app/components/customerDashboard/affiliate/affiliatemyteam/AffiliateTeamWrapp.jsx
app/components/customerDashboard/affiliate/affiliatemyteam/MyTeamList.jsx

 grand total calculation

---

app/(customerdashboard)/(affiliate)/affiliateteam/[userId]/page.jsx
app/components/customerDashboard/affiliate/affiliatemyteam/AffiliateTeamWrapp.jsx
app/services/affiliate/getAffiliateMembersTeam.js
app/services/affiliate/getAffiliateTeam.js

my team pesinition code update

my team pesinition code update

---

app/components/customerDashboard/affiliate/affiliatedashboard/AffiliateReferFriend.jsx
app/components/customerDashboard/affiliate/affiliatemyteam/AffiliateTeamWrapp.jsx
app/ref/[id]/page.jsx
app/registration/page.jsx
app/services/affiliate/getAffiliateReferralCode.js
package-lock.json
package.json

Referral Link copied work done

Referral Link copied work done

---

app/components/customerDashboard/affiliate/affiliatedashboard/AffiliateReferFriend.jsx
app/utils.js

vercel link add in utils file

---

app/cart-page/CartPageInfo.jsx
app/components/AddToCartButton.jsx
app/components/Header.jsx
app/components/Like.jsx
app/services/postAddToCardInfo.js
app/shipping-page/cart-product/AddToCartProductShippingPage.jsx

console error and warning solve

console error and warning solve

---

app/components/customerDashboard/affiliate/affiliatedashboard/AffiliateReferFriend.jsx
app/components/customerDashboard/dashboard/AffiliatePartnerStatus.jsx
app/components/customerDashboard/dashboard/CustomerDashboardRightSide.jsx
app/components/customerDashboard/dashboard/DashboardTopInfo.jsx
app/orderinvoice/page.jsx
app/orderview/page.jsx
app/registration/page.jsx
app/services/affiliate/getApplyForAffiliate.js
app/services/userdashboard/getUserDashboard.js

apply for affiliate api work

---

app/(customerdashboard)/(affiliate)/affiliateteam/[userId]/page.jsx
app/components/customerDashboard/CustomerLeftSideNavbar.jsx
app/components/customerDashboard/affiliate/affiliatedashboard/AffiliateDashboardRank.jsx
app/components/customerDashboard/affiliate/affiliatedashboard/AffiliateDashboardWrapp.jsx
app/components/customerDashboard/affiliate/affiliatedashboard/AffiliateReferFriend.jsx
app/components/customerDashboard/affiliate/affiliatemyteam/AffiliateTeamWrapp.jsx
app/components/customerDashboard/affiliate/affiliatemyteam/MyTeamList.jsx
app/components/customerDashboard/affiliate/affiliatemyteam/SearchMyTeam.jsx
app/components/customerDashboard/affiliate/affiliatemyteam/TeamListNotFound.jsx
app/components/customerDashboard/dashboard/AffiliatePartnerStatus.jsx
app/registration/page.jsx
app/services/affiliate/getAffiliateNewSignup.js

affiliate new signup

---

app/components/customerDashboard/affiliate/affiliatedashboard/AffiliateDashboardRank.jsx
app/registration/page.jsx

affiliate new signup work done

affiliate new signup work done

---

app/(customerdashboard)/layout.js
app/(customerdashboard)/orderhistory/page.jsx
app/components/MobileNav.jsx
app/components/customerDashboard/affiliate/affiliateproducts/AffiliateProductDetails.jsx
app/components/customerDashboard/affiliate/affiliateproducts/AffiliateRetailsProduct.jsx
app/components/customerDashboard/affiliate/affiliateproducts/ContainerBooking.jsx
app/components/customerDashboard/affiliate/affiliateproducts/ResaleProductDetailsContent.jsx
app/components/customerDashboard/dashboard/CustomerDashboardRightSide.jsx
app/components/customerDashboard/manageProfile/ManageProfileItem.jsx/ManageBasicInfo.jsx
app/components/customerDashboard/manageProfile/ManageProfileItem.jsx/ManageIDVerification.jsx
app/components/customerDashboard/manageProfile/ManageProfileItem.jsx/ManageNomineeInfo.jsx
app/components/orderview/OrderViewWrapp.jsx
app/container-product-details/[...id]/page.jsx
app/orderinvoice/page.jsx
app/products/[slug]/ProductDetails.jsx
app/ref/[id]/page.jsx
app/resale-product-details/[Id]/page.jsx

loading... issue redesign

---

app/(customerdashboard)/orderhistory/page.jsx
app/components/customerDashboard/orderhistory/CustomerRightsids.jsx
app/services/userdashboard/postOrderCancel.js

cancel order API working done

---

app/components/customerDashboard/dashboard/CustomerDashboardRightSide.jsx
app/components/customerDashboard/orderhistory/CustomerRightsids.jsx
app/services/userdashboard/deleteShippingAddress.js

Delete Shipping Address API working Done

Delete Shipping Address API working Done

---

app/cart-page/CartPageInfo.jsx

cart page items count

---

app/cart-page/CartPageInfo.jsx
app/components/AddToCartButton.jsx
app/components/shippingPage/ShippingProduct.jsx

discountPrice convert to reqularPrice

discountPrice convert to reqularPrice

---

app/components/customerDashboard/affiliate/affiliatedashboard/AffiliateDashboardBonusDataTable.jsx
app/components/customerDashboard/affiliate/affiliatedashboard/AffiliateDashboardChartAndData.jsx
app/components/customerDashboard/affiliate/affiliatedashboard/AffiliateDashboardWrapp.jsx
app/components/customerDashboard/affiliate/affiliateproducts/AffiliateProductDetailsImg.jsx
app/components/customerDashboard/affiliate/affiliateproducts/ResaleListViewProductInfo.jsx
app/components/customerDashboard/affiliate/affiliateproducts/ResaleProductDetailsContent.jsx
app/components/customerDashboard/affiliate/affiliateproducts/ResaleProductsInfo.jsx
app/components/productDetail/ResaleCondition.jsx
app/components/productDetail/ResaleProductLongDescription.jsx
app/resale-product-details/[...Id]/page.jsx
app/services/affiliate/getAffiliateIncomeHistory.js

income history and resale details api working

income history and resale details api working

---

app/components/customerDashboard/affiliate/affiliatedashboard/AffiliateDashboardBonusDataTable.jsx
app/components/customerDashboard/affiliate/affiliatedashboard/ApexChart.jsx
app/components/customerDashboard/affiliate/affiliateproducts/AffiliateRetailsProductInfo.jsx
app/components/customerDashboard/affiliate/affiliateproducts/ContainerBooking.jsx
app/components/customerDashboard/affiliate/affiliateproducts/ContainerBookingProduct.jsx
app/components/customerDashboard/affiliate/affiliateproducts/ContainerOrderDetails.jsx
app/components/customerDashboard/affiliate/affiliateproducts/ResaleProductsInfo.jsx
app/container-product-details/[...id]/page.jsx
app/services/affiliate/affiliateproducts/postContainerPlaceOrder.js
app/services/affiliate/getAffiliateIncomeChart.js

container booking now api working done

container booking now api working done

---

app/components/customerDashboard/affiliate/affiliateproducts/ContainerOrderDetails.jsx
app/components/customerDashboard/affiliate/affiliaterankreward/AffiliateRankWrapp.jsx
app/components/customerDashboard/affiliate/affiliaterankreward/RankRewardList.jsx
app/components/paynow/PayNowSummary.jsx
app/services/affiliate/getContainerOrderSummery.js
app/thankyou/page.jsx

container order summary API work Done

container order summary API work Done

---

app/components/customerDashboard/affiliate/affiliatedashboard/ApexChart.jsx
app/services/affiliate/getAffiliateIncomeChart.js

income chart

---

app/components/customerDashboard/affiliate/affiliatedashboard/ApexChart.jsx
app/components/customerDashboard/affiliate/affiliateproducts/AffiliateRetailsProductInfo.jsx
app/components/customerDashboard/affiliate/affiliateproducts/RetailListViewProductInfo.jsx

length optional checcking

---

app/components/customerDashboard/affiliate/affiliatedashboard/ApexChart.jsx
app/components/customerDashboard/affiliate/affiliateproducts/ContainerBooking.jsx
app/components/customerDashboard/affiliate/affiliateproducts/ContainerBookingProduct.jsx
app/components/customerDashboard/affiliate/affiliateproducts/ContainerOrderDetails.jsx
app/components/customerDashboard/affiliate/affiliateproducts/ContainerTopInfo.jsx

chart working done

---

app/components/customerDashboard/payout/AffiliateBonusDetail.jsx
app/components/customerDashboard/payout/AffiliateBonusWrapper.jsx
app/services/affiliatepayout/getPayoutAffiliateBonus.js

affiliate bonus api

---

app/components/customerDashboard/payout/AffiliateBonusDetail.jsx
app/components/customerDashboard/payout/AffiliateBonusWrapper.jsx
app/components/customerDashboard/payout/GenerationBonusDetail.jsx
app/components/customerDashboard/payout/GenerationBonusWrapper.jsx
app/components/customerDashboard/payout/PayoutRankRewardDetail.jsx
app/components/customerDashboard/payout/PayoutRankRewardWrapper.jsx
app/components/customerDashboard/payout/ResaleBonusDetail.jsx
app/components/customerDashboard/payout/ResaleBonusWrapper.jsx
app/services/affiliatepayout/getAffiliateGenerationCommission.js
app/services/affiliatepayout/getPayoutRankReward.js
app/services/affiliatepayout/getPayoutResaleBonus.js

payout api implement

---

app/components/customerDashboard/payout/AffiliateBonusDetail.jsx
app/components/customerDashboard/payout/AffiliateBonusWrapper.jsx
app/components/customerDashboard/payout/GenerationBonusDetail.jsx
app/components/customerDashboard/payout/PayoutSearchForm.jsx
app/components/customerDashboard/payout/ResaleBonusDetail.jsx
app/components/customerDashboard/payout/ResaleBonusWrapper.jsx
app/services/affiliatepayout/getAffiliateGenerationCommission.js
app/services/affiliatepayout/getPayoutAffiliateBonus.js
app/services/affiliatepayout/getPayoutRankReward.js
app/services/affiliatepayout/getPayoutResaleBonus.js

affiliate bonus search functionality done

affiliate bonus search functionality done

---

app/components/customerDashboard/payout/GenerationBonusWrapper.jsx
app/components/customerDashboard/payout/PayoutRankRewardWrapper.jsx
app/components/customerDashboard/payout/ResaleBonusDetail.jsx
app/components/customerDashboard/payout/ResaleBonusWrapper.jsx

search working in payout page done

search working in payout page done

---

app/components/customerDashboard/payout/GenerationBonusDetail.jsx
app/components/customerDashboard/payout/PayoutSalaryDetail.jsx
app/components/customerDashboard/payout/PayoutSalaryWrapper.jsx
app/components/customerDashboard/payout/ResaleBonusDetail.jsx

৳ added on payout page

---

app/components/customerDashboard/CustomerLeftSideNavbar.jsx
app/components/customerDashboard/affiliate/affiliaterankreward/ClaimRewardModal.jsx
app/components/customerDashboard/affiliate/affiliaterankreward/RankRewardList.jsx
app/components/customerDashboard/affiliate/affiliaterankreward/RankRewardTop.jsx
app/login/page.jsx
app/services/rankreward/postAffiliateRankRewards.js

claim reward

---

app/components/customerDashboard/dashboard/CustomerDashboardRightSide.jsx
app/components/customerDashboard/payout/AffiliateBonusWrapper.jsx
app/components/customerDashboard/payout/GenerationBonusWrapper.jsx
app/components/customerDashboard/payout/PayoutRankRewardDetail.jsx
app/components/customerDashboard/payout/PayoutRankRewardWrapper.jsx
app/components/customerDashboard/payout/PayoutSalaryDetail.jsx
app/components/customerDashboard/payout/PayoutSalaryWrapper.jsx
app/components/customerDashboard/payout/PayoutSearchForm.jsx
app/components/customerDashboard/payout/ResaleBonusWrapper.jsx

payout page loading code optimize

payout page loading code optimize

---

app/services/affiliate-finance/getAffiliateFinanceBalanceChart.js
app/services/affiliate-finance/getAffiliateFinanceWithdraw.js
app/services/affiliate-finance/getAffiliateFinanceWithdrawHistory.js
app/services/affiliate-finance/getFinanceWithdrawHistoryById.js

affiliate finance service create

affiliate finance service create

---

app/components/customerDashboard/affiliate/affiliaterankreward/AffiliateRankWrapp.jsx
app/components/customerDashboard/affiliate/affiliaterankreward/ClaimRewardModal.jsx
app/components/customerDashboard/affiliate/affiliaterankreward/RankRewardList.jsx

status change

---

app/components/customerDashboard/affiliate/affiliaterankreward/AffiliateRankWrapp.jsx

statusChange

---

app/components/customerDashboard/affiliate/affiliaterankreward/ClaimRewardModal.jsx
app/components/customerDashboard/affiliate/affiliaterankreward/RankRewardList.jsx

color change

---

app/components/customerDashboard/finance/WithdrawChart.jsx
app/components/customerDashboard/finance/WithdrawTopBanner.jsx
app/services/affiliate-finance/getFinanceBankTransferInfo.js
app/services/affiliate-finance/getFinanceMobileBankingInfo.js

chart api done

---

app/(customerdashboard)/(finance)/finance-bank-info/page.jsx
app/(customerdashboard)/(finance)/finance-my-bank-details/page.jsx
app/components/customerDashboard/finance/AffiliateBonusWrapper.jsx
app/components/customerDashboard/finance/AgentWithdrawalModal.jsx
app/components/customerDashboard/finance/BankDetailsInfo.jsx
app/components/customerDashboard/finance/BankDetailsWrapper.jsx
app/components/customerDashboard/finance/MobileBankingInfo.jsx
app/components/customerDashboard/finance/MobileBankingModal.jsx
app/components/customerDashboard/finance/WithdrawChart.jsx
app/components/customerDashboard/finance/WithdrawTopBanner.jsx
app/services/affiliate-finance/getFinanceMobileBankingInfo.js

Finance chart api

---

app/components/customerDashboard/orderhistory/SaleOnNagadhatBottom.jsx
app/components/customerDashboard/orderhistory/SaleOnNagadhatHeader.jsx
app/components/customerDashboard/orderhistory/SaleOnNagadhatInvoice.jsx
app/components/customerDashboard/orderhistory/SaleOnNagadhatModal.jsx
app/components/customerDashboard/orderhistory/SaleOnNagadhatTop.jsx
app/components/customerDashboard/orderhistory/SaleOnNagadhatWallet.jsx
package-lock.json
package.json

create component sale on Nagadhat page

create componet sale on Nagadhat page

---

app/(customerdashboard)/(affiliate)/affiliat-sell-on-nagadhat/[id]/page.jsx
app/components/customerDashboard/affiliate/sellOnNagadhat/SellOnNagadhatHistory.jsx
app/components/customerDashboard/orderhistory/SaleOnNagadhatModal.jsx
app/services/affiliate/getLocalIpAddress.js
package-lock.json
package.json

find ip addres

---

app/components/customerDashboard/finance/AffiliateBonusWrapper.jsx
app/components/customerDashboard/finance/AgentWithdrawalModal.jsx
app/components/customerDashboard/finance/BankWithdrawalModal.jsx
app/components/customerDashboard/finance/LastFiveWithdrawHistory.jsx
app/components/customerDashboard/finance/WithdrawHistory.jsx
app/components/customerDashboard/finance/WithdrawHistoryBtn.jsx
app/components/customerDashboard/finance/WithdrawHistoryModal.jsx
app/components/customerDashboard/manageProfile/ManageProfileItem.jsx/ManageNomineeInfo.jsx
app/components/customerDashboard/orderhistory/CustomerRightsids.jsx
app/services/affiliate-finance/getAffiliateFinanceAgents.js

affiliate-finance-bank-transfer API work done

affiliate-finance-bank-transfer API work done

---

app/cart-page/CartPageInfo.jsx
app/components/shippingPage/ShippingOrderSection.jsx
app/components/shippingPage/ShippingProduct.jsx
app/components/shippingPage/customerAddress/CustomerAddress.jsx

added space in cart page

---

app/components/customerDashboard/affiliate/saleonnagadhatdetail/SaleOnNagadhatDetailBottom.jsx
app/components/customerDashboard/affiliate/saleonnagadhatdetail/SaleOnNagadhatDetailHeader.jsx
app/components/customerDashboard/affiliate/saleonnagadhatdetail/SaleOnNagadhatDetailPay.jsx
app/components/customerDashboard/affiliate/saleonnagadhatdetail/SellOnNgadhatDetailWrapp.jsx
app/layout.js
public/css/sale-on-nagadhat.css

print cs on sale on nagadhat

---

app/components/customerDashboard/affiliate/saleonnagadhatdetail/SaleOnNagadhatDetailBottom.jsx
app/components/customerDashboard/affiliate/saleonnagadhatdetail/SaleOnNagadhatDetailNomini.jsx
app/components/customerDashboard/finance/LastFiveWithdrawHistory.jsx
app/components/customerDashboard/orderhistory/SaleOnNagadhatModal.jsx
app/components/customerDashboard/orderhistory/SaleOnNagadhatWallet.jsx
app/components/ordersummary/OrderSummaryLeft.jsx
app/components/paynow/PayNowDetails.jsx
app/components/paynow/PayNowPaymentOption.jsx
app/components/paynow/PayNowSummary.jsx
app/components/paynow/PayWithAgentModal.jsx
public/css/sale-on-nagadhat.css

agent payment modal design

---

app/components/paynow/PayNowDetails.jsx
app/components/paynow/PayNowPaymentOption.jsx
app/components/paynow/PayNowSummary.jsx

select check box then show modal

select check box then show modal

---

app/components/paynow/PayNowDetails.jsx
app/components/paynow/PayNowPaymentOption.jsx
app/components/paynow/PayNowSummary.jsx
app/paynow/page.jsx

dynamic import

---

app/components/paynow/PayNowPaymentOption.jsx
app/components/paynow/PayNowSummary.jsx
app/components/paynow/PayWithAgentModal.jsx
app/components/paynow/PayWithBankModal.jsx
app/services/affiliate-finance/getPayAgentLists.js

agent list

---

app/components/customerDashboard/orderhistory/CustomerRightsids.jsx
app/components/paynow/PayNowPaymentOption.jsx
app/components/paynow/PayWithAgentModal.jsx
app/components/paynow/PayWithBankModal.jsx
app/components/paynow/PayWithBankModalLeft.jsx
app/components/paynow/PayWithBankModalRight.jsx

pay with bank modal page design

pay with bank modal page design

---

app/components/paynow/BankSubmitPaymentBtn.jsx
app/components/paynow/PayCompletedOrderBtn.jsx
app/components/paynow/PayNowDetails.jsx
app/components/paynow/PayNowPaymentOption.jsx
app/components/paynow/PayNowSummary.jsx
app/components/paynow/PayWithAgentModal.jsx
app/components/paynow/PayWithBankModal.jsx
app/components/paynow/PayWithBankModalLeft.jsx
app/components/paynow/PayWithBankModalRight.jsx
app/components/paynow/PayWithBankModalTop.jsx
app/services/bank/PostOrderFullPaymentWithBank.js
app/services/bank/getBankLists.js

payment wit bank

---

app/(customerdashboard)/(finance)/finance-withdraw-request/[id]/page.jsx
app/cart-page/CartPageInfo.jsx
app/components/customerDashboard/finance/AgentWithdrawalModal.jsx
app/components/customerDashboard/finance/BankDetailsInfo.jsx
app/components/customerDashboard/finance/MobileBankingInfo.jsx
app/components/shippingPage/ShippingProduct.jsx

User Bank Info add

---

app/(customerdashboard)/(payout)/payout-salary/page.jsx
app/components/customerDashboard/payout/PayoutSalaryDate.jsx
app/components/customerDashboard/payout/PayoutSalaryDetail.jsx
app/components/customerDashboard/payout/PayoutSalaryWrapper.jsx
app/services/affiliatepayout/getAffiliateSalary.js

affiliate salary API Implement

affiliate salary API Implement

---

app/components/paynow/PayWithBankModalRight.jsx

bank modal page change

---

app/components/paynow/PayNowSummary.jsx

Due Price Calculation

---

app/components/MobileNav.jsx
app/components/customerDashboard/orderhistory/CustomerRightsids.jsx
app/paynow/page.jsx
public/css/responsive.css

order histy and order-status change

order histy and order-status change

---

app/components/MobileNav.jsx
app/components/paynow/PayNowPaymentOption.jsx
app/components/paynow/PayWithBankModalRight.jsx
public/css/responsive.css

change more

---

app/components/MobileNav.jsx

anywhere click then modal hide

anywhere click then modal hide

---

app/components/customerDashboard/CustomerLeftSideNavbar.jsx
app/components/discountPartner/DiscountPartnerInfo.jsx
app/components/discountPartner/DiscountPartnerTop.jsx
app/components/discountPartner/DiscountPartnerWrapper.jsx
app/components/discountPartner/FilterCategories.jsx
app/discount-partners-page/page.jsx

Discount Partners page design

---

app/components/paynow/PayCompletedOrderBtn.jsx
app/components/paynow/PayNowSummary.jsx
app/components/paynow/PayWithBankModalRight.jsx
app/components/paynow/PayWithBankModalTop.jsx

required validation added in bank modal

required validation added in bank modal

---

app/cart-page/CartPageInfo.jsx
app/components/ordersummary/OrderProductItems.jsx

regular price update

---

app/(customerdashboard)/privilege-card-shopping-list/page.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardDashboardTop.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardModal.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProduct.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductSummary.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductTable.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductTop.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardShoppingSummary.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardShoppingTable.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardShoppingWrapper.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeMainCard.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeProductDetailModal.jsx
app/components/paynow/PayNowPaymentOption.jsx
app/components/paynow/PayNowSummary.jsx

privilege card dashboard design

privilege card dashboard design

---

app/components/customerDashboard/orderhistory/SaleOnNagadhatModal.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductTable.jsx

agreement message showing on sale on nagadhat modal

aggrement message showing on sale on nagadhat modal

---

app/(customerdashboard)/privilege-rebate-records/page.jsx
app/(customerdashboard)/wallet-statement/page.jsx
app/components/customerDashboard/CustomerLeftSideNavbar.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeRebateRecordData.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeRebateRecordWrapper.jsx
app/components/customerDashboard/privilegeDashboard/WalletStatementData.jsx
app/components/customerDashboard/privilegeDashboard/WalletStatementWrapper.jsx

Privilege Rebate Record page design

Privilege Rebate Record

---

app/components/customerDashboard/affiliate/affiliaterankreward/ClaimRewardModal.jsx
app/components/discountPartner/PartnerDetailImage.jsx
app/components/discountPartner/PartnerDetailInfoRight.jsx

reward page work

---

app/components/discountPartner/DiscountPartnerInfo.jsx
app/components/discountPartner/DiscountPartnerWrapper.jsx
app/components/discountPartner/FilterCategories.jsx
app/components/discountPartner/PartnerDetailImage.jsx
app/components/discountPartner/PartnerDetailInfo.jsx
app/components/discountPartner/PartnerDetailInfoRight.jsx
app/components/discountPartner/PartnerDetailsWrapper.jsx
app/discount-partners-page/[id]/page.jsx
app/discount-partners-page/page.jsx
app/services/discountPartner/getDiscountPartnerDetailsBySlug.js
app/services/discountPartner/getDiscountPartnerList.js
app/services/discountPartner/getServiceCategoryWithDiscountPartner.js

discount partner API Implement

discount partner Api Implement

---

app/components/merchant/EasySellStepImg.jsx
app/components/merchant/GetLoans.jsx
app/components/merchant/MerchantVideo.jsx
app/components/merchant/MerchantVisitNow.jsx
app/components/merchant/MerchantWrapper.jsx
app/components/merchant/ReferSellerImg.jsx
app/components/merchant/ShouldISellTheNagadhatImg.jsx
app/components/merchant/StartSellingImg.jsx
app/components/merchant/WelcomeImg.jsx

component for Merchant page

---

app/affiliate/page.jsx
app/components/affiliatePage/AffiliateWrapper.jsx
public/css/common.css
public/css/responsive.css

affiliate page

---

app/components/discountPartner/DiscountPartnerInfo.jsx
app/components/discountPartner/PartnerDetailImage.jsx
app/components/discountPartner/PartnerDetailsWrapper.jsx
app/discount-partners-page/[id]/page.jsx
app/discount-partners-page/page.jsx

added to private route in discount partner page

added to private route in discount partner page

---

app/components/customerDashboard/finance/BankDetailsInfo.jsx
app/components/customerDashboard/finance/MobileBankingInfo.jsx
app/components/discountPartner/PartnerDetailImage.jsx
app/components/discountPartner/PartnerDetailInfoRight.jsx
app/components/paynow/PayCompletedOrderBtn.jsx
app/components/paynow/PayNowPaymentOption.jsx
app/components/shippingPage/customerAddress/CustomerAddress.jsx

discount partner details page image gallery added

discount partner details page image gallery added

---

app/components/discountPartner/PartnerDetailImage.jsx
app/components/discountPartner/PartnerDetailInfo.jsx
app/components/discountPartner/PartnerDetailsWrapper.jsx
app/components/discountPartner/PartnerImageSlider.jsx
public/css/common.css

partner slider design change

---

app/components/customerDashboard/affiliate/saleonnagadhatdetail/SaleOnNagadhatDetailPay.jsx

toFixed method add in byagreement page

toFixed method add in byagreement page

---

app/components/CategoryMainMenuList.jsx
app/components/ProductCategoryItem.jsx

home page category & brand image url path change

home page category & brand image url path change

---

app/components/Category.jsx
app/components/ProductBrands.jsx
app/components/ProductBrandsItem.jsx

home page brand component create

home page brand component create

---

app/components/CategoryMainMenuList.jsx
app/components/ProductCategoryItem.jsx

iamge patch change

---

app/(customerdashboard)/(affiliate)/affiliateteam/[userId]/page.jsx

affiliate team page added a transition hook

affiliate team page added a transition hook

---

app/components/MainNav.jsx

Debouncing in header product search

Debouncing in header product search

---

app/components/MainNav.jsx
app/components/MobileNav.jsx

fetchSearchProduct fucntion added a Debouncing

fetchSearchProduct fucntion added a Debouncing

---

app/components/customerDashboard/affiliate/affiliatemyteam/AffiliateTeamWrapp.jsx
app/components/customerDashboard/affiliate/affiliatemyteam/MyTeamList.jsx

useTransition add to a affiliate team page

useTransition add to a affiliate team page

---

app/components/MainNav.jsx
app/components/customerDashboard/affiliate/affiliatemyteam/AffiliateTeamWrapp.jsx

delete session in useefect

---

app/components/MainNav.jsx
app/components/MobileNav.jsx
app/components/ProductSearchResult.jsx
app/components/ProductSearchResultMobile.jsx
next.config.mjs
public/css/responsive.css
public/css/search-modal.css

 z-index change

---

app/components/Sales.jsx

flash sale end point

---

app/components/AddToCartButton.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductTable.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductTop.jsx

privilege product list showing

privilege product list showing

---

app/components/customerDashboard/privilegeDashboard/PrivilegeBuyNowBtn.jsx

isLoading added in privilege buy now button

isLoading added in privilege buy now button

---

app/components/customerDashboard/affiliate/affiliatemyteam/AffiliateTeamWrapp.jsx
app/components/customerDashboard/affiliate/affiliateproducts/AffiliateRetailsProduct.jsx
app/components/customerDashboard/affiliate/affiliateproducts/AffiliateRetailsProductInfo.jsx
app/components/customerDashboard/affiliate/affiliateproducts/ContainerBooking.jsx

checking and aded in to isloading state

checking and aded in to isloading state

---

app/components/customerDashboard/privilegeDashboard/PrivilegeBuyNowBtn.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardDashboardTop.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeMainCard.jsx

status change in privilege cart

status change in privilege cart

---

app/cart-page/CartPageInfo.jsx
app/components/shippingPage/ShippingProduct.jsx

remove console log

---

app/components/customerDashboard/affiliate/affiliateproducts/ContainerBookingProduct.jsx
app/components/customerDashboard/affiliate/affiliateproducts/ContainerTopInfo.jsx

container image issue fixed

---

app/components/customerDashboard/affiliate/affiliateproducts/ContainerBookingProduct.jsx

seizes remove in container page

seizes remove in container page

---

app/components/customerDashboard/privilegeDashboard/PrivilegeAddToCard.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProduct.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductSummary.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductTable.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductTableBody.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeDeleteCardItem.jsx

privilege cart page working

---

app/components/customerDashboard/privilegeDashboard/DeletePrivilegeCartProduct.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductSummary.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductTableBody.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardShoppingTable.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardShoppingWrapper.jsx
app/services/getDeleteCartProduct.js
app/services/privilegeCard/getPrivilegeAddToCartProducts.js

privilege card item delete api done

privilege card item delete api done

---

app/components/customerDashboard/privilegeDashboard/PrivilegeAddToCard.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProduct.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductSummary.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductTable.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductTableBody.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardShoppingWrapper.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeDeleteCardItem.jsx

checking limit price and quantity

checking limit price and quantity

---

app/components/customerDashboard/privilegeDashboard/PrivilegeCardProduct.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductSummary.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductTable.jsx
app/shipping-page/cart-product/AddToCartProductShippingPage.jsx

isloading and privilege dashboard page checkout API done

isloading and privilege dashboard page checkout API done

---

app/components/DivisionList.jsx
app/components/customerDashboard/dashboard/ShippingAddressModal.jsx
app/components/customerDashboard/finance/BankWithdrawalModal.jsx
app/components/customerDashboard/finance/LastFiveWithdrawHistory.jsx
app/components/customerDashboard/finance/MobileBankingModal.jsx
app/components/customerDashboard/finance/TransferVerifyOTPModal.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCancelledModal.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeChooseOptionBtn.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeMainCard.jsx
app/components/customerDashboard/privilegeDashboard/ShowingProductPrices.jsx
app/components/discountPartner/DiscountPartnerBusinessInfo.jsx
app/components/discountPartner/DiscountPartnerComfarmModal.jsx
app/components/paynow/PayWithBkashModal.jsx
app/hooks/useCountdown.js
app/hooks/useScreenSize.js
app/utils.js

cancel privilege page design

---

app/components/customerDashboard/affiliate/affiliateproducts/ContainerBooking.jsx
app/components/customerDashboard/affiliate/affiliateproducts/ContainerHorizontalScroll.jsx
public/css/customer-affiliate-dashboard.css

container new design

---

app/components/customerDashboard/affiliate/affiliateproducts/ContainerBooking.jsx
app/components/customerDashboard/affiliate/affiliateproducts/ContainerOrderDetails.jsx
app/container-product-details/[...id]/loading.jsx
app/container-product-details/[...id]/page.jsx
app/services/affiliate/affiliateproducts/getAffiliateContainer.js

query params added to container API

query params added to container API

---

app/(customerdashboard)/support/page.jsx
app/components/customerDashboard/CustomerLeftSideNavbar.jsx

support page create

---

app/components/customerDashboard/CustomerLeftSideNavbar.jsx
app/components/customerDashboard/affiliate/affiliateproducts/ContainerHorizontalScroll.jsx
public/css/customer-affiliate-dashboard.css

container product top tab change

container product top tab change

---

app/services/getProductDetails.js

revalidate time decrement in product details page

revalidate time decrement in product details page

---

app/affiliate-terms-condition/page.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductTableBody.jsx
public/css/service.css

terms and condition page design done

terms and condition page design done

---

app/components/customerDashboard/CustomerLeftSideNavbar.jsx
public/css/customer-dashboard.css

left sidebar menu hover and active color change

left sidebar menu hover and active color change

---

app/components/customerDashboard/privilegeDashboard/PrivilegeRebateRecordData.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeRebateRecordWrapper.jsx
app/components/customerDashboard/privilegeDashboard/WalletStatementData.jsx
app/components/customerDashboard/privilegeDashboard/WalletStatementWrapper.jsx
app/services/privilegeCard/getPrivilegeCardRebateRecord.js
app/services/privilegeCard/getPrivilegeCardWalletStatement.js

Wallet Statement page working Done

Wallet Statement page working Done

---

app/components/customerDashboard/privilegeDashboard/PrivilegeRebateRecordData.jsx

Rebate History page working Done

Rebate History page working Done

---

app/services/privilegeCard/getPrivilegeCardShoppingChoiceDetail.js

shopping choice detail API service create

shopping choice detail API service create

---

app/components/customerDashboard/privilegeDashboard/PrivilegeChooseOptionBtn.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeMainCard.jsx
app/components/customerDashboard/privilegeDashboard/ShowingProductPrices.jsx
app/services/privilegeCard/getPrivilegeCardBalanceAfterChoose.js

privilege-card-shopping-choice-detail API Working Done

privilege-card-shopping-choice-detail API Working Done

---

app/components/customerDashboard/privilegeDashboard/PrivilegeCardDashboardTop.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductTable.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductTableBody.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeProductDetailModal.jsx
public/css/common.css

privilege-card-balance-after-choose API Working done

privilege-card-balance-after-choose API Working done

---

app/components/FlipClock.jsx
app/components/Sales.jsx
app/components/viewAllProduct/ViewAllBanner.jsx
app/components/viewAllProduct/ViewAllCategoryTitle.jsx
public/css/responsive.css

all-flashsales-product page Ending in responsive issue fixed

all-flashsales-product page Ending in responsive issue fixed

---

app/components/customerDashboard/affiliate/affiliatedashboard/AffiliateDashboardInfo.jsx
app/components/customerDashboard/dashboard/DashboardTopInfo.jsx

customer dashboard withdrawable text added

customer dashboard withdrawable text added

---

app/services/getCategoryMenu.js
app/services/getHomeCategoryList.js
app/services/getHomeFlashSalesProduct.js
app/services/getHomePageBodyBrand.js
app/services/getHomeSlider.js

revalidate change in API

---

app/services/getHomeCategoryList.js
app/services/getHomeFlashSalesProduct.js
app/services/getHomePageBodyBrand.js

brand and category api remove tags in next js

brand and category api remove tags in next js

---

app/components/customerDashboard/affiliate/affiliatedashboard/AffiliateDashboardInfo.jsx
app/components/customerDashboard/dashboard/DashboardTopInfo.jsx
app/components/customerDashboard/finance/FinanceHistoryModalTable.jsx
app/components/customerDashboard/finance/WithdrawHistory.jsx
app/components/customerDashboard/finance/WithdrawTopBanner.jsx

Withdraw blance title name change

Withdraw blance title name change

---

app/components/customerDashboard/payout/AffiliateBonusDetail.jsx
app/components/customerDashboard/payout/GenerationBonusDetail.jsx
app/components/customerDashboard/payout/PayoutSalaryDetail.jsx
app/components/customerDashboard/payout/ResaleBonusDetail.jsx

payout section all page table responsive and total amount showing

payout section all page table responsive and total amount showing

---

app/components/customerDashboard/finance/FinanceHistoryModalTable.jsx
app/components/customerDashboard/finance/FinancePaymentMethod.jsx
app/components/customerDashboard/finance/LastFiveWithdrawHistory.jsx
app/components/customerDashboard/finance/WithdrawHistory.jsx
public/css/responsive.css

finance section all table response issue fixed

finance section all table response issue fixed

---

app/components/paynow/BankSubmitPaymentBtn.jsx
app/components/paynow/PayWithBankModalRight.jsx

Submit Payment btn disable loading event functionality added

Submit Payment btn disable loading event functionality added

---

app/utils.js

BaseUrl change

---

app/components/customerDashboard/privilegeDashboard/PrivilegeMainCard.jsx

not Membership Card then showing cancel button

not Membership Card then showing cancel button

---

app/components/customerDashboard/payout/PendingBalanceLists.jsx
app/components/customerDashboard/payout/PendingBalanceWrapper.jsx

affiliate-pending-balance API implement

affiliate-pending-balance API impliment

---

app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductSummary.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductTable.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeProductDetailModal.jsx

privilege card view cart btn design change

privilege card view cart btn design change

---

app/components/ProductCard.jsx
app/components/viewAllProduct/ViewAllProductItems.jsx
app/utils.js

wishlist button hide in all page

wishlist button hide in all page

---

app/components/customerDashboard/dashboard/DashboardTopInfo.jsx
public/css/customer-dashboard.css

Dashboard top 4 box design responsive issue fixed

Dashboard top 4 box design responsive issue fixed

---

app/utils.js

dev link change

---

app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductTable.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductTop.jsx
public/css/responsive.css

privilege card page space decrease

privilege card page space decrease

---

app/components/customerDashboard/affiliate/affiliatedashboard/AffiliateReferFriend.jsx

affiliate dashboard copy link text black color added

affiliate dashboard copy link text black color added

---

app/components/paynow/PayNowPaymentOption.jsx

pay now page check terms & condition button highlight functionality added

pay now page check terms & condition button highlight functionality added

---

app/components/ordersummary/OrderSummaryLeft.jsx

agent and bank text add in thank you page

agent and bank text add in thank you page

---

app/(customerdashboard)/(privilegeCard)/privilege-card-shopping-list/page.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeBuyNowBtn.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCancelledModal.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardDashboardTop.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProduct.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeMainCard.jsx

cancel status in privilege card page

cancel status in privilege card page

---

app/components/customerDashboard/affiliate/affiliateproducts/ContainerOrderDetails.jsx

toFixed functionality added in container product

toFixed functionality added in container product

---

app/components/customerDashboard/affiliate/affiliaterankreward/AffiliateRankWrapp.jsx
app/components/customerDashboard/affiliate/affiliaterankreward/ClaimRewardModal.jsx
app/components/customerDashboard/affiliate/affiliaterankreward/RankRewardList.jsx

Reward Claim then modal close functionality added

Reward Claim then modal close functionality added

---

app/components/customerDashboard/privilegeDashboard/PrivilegeBuyNowBtn.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardDashboardTop.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductTableBody.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeMainCard.jsx
app/components/ordersummary/OrderSummaryLeft.jsx

privilege card membership card issue fixed

privilege card membership card issue fixed

---

app/(customerdashboard)/(privilegeCard)/privilege-card-shopping-list/page.jsx
app/components/customerDashboard/affiliate/affiliateproducts/ShippingOrderSectionResale.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductSummary.jsx
app/components/ordersummary/OrderSummaryLeft.jsx
app/shipping-page-resale/[orderId]/page.js

privilege card Proceed to Checkout new functionality added

privilege card Proceed to Checkout new functionality added

---

app/components/customerDashboard/finance/BankDetailsInfo.jsx
app/components/customerDashboard/finance/MobileBankingInfo.jsx
app/shipping-page/buy-now/BuyNowShippingProductPage.jsx
app/shipping-page/cart-product/AddToCartProductShippingPage.jsx

Place Order API Added to a cart-product-type

PlaceOrder API Added to a cart-product-type

---

app/(customerdashboard)/(finance)/finance-transactions/page.jsx

finance-transactions page to Fixed functionality added

finance-transactions page toFixed functionality added

---

app/components/customerDashboard/affiliate/affiliatedashboard/AffiliateDashboardBonusDataTable.jsx

affiliate dashboard bonus table page issue fixed

affiliate dashboard bonus table page issue fixed

---

app/components/customerDashboard/finance/TransferVerifyOTPModal.jsx

Transfer Verify OTP Modal tofixed issue solved

TransferVerifyOTPModal tofixed issue solved

---

app/components/customerDashboard/finance/TransferVerifyOTPModal.jsx

parseInt method in Transfer Verify OTP Modal

parseInt method in Transfer Verify OTP Modal

---

app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductSummary.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductTable.jsx

privilege card Proceed to Checkout button disable functionality added

privilege card Proceed to Checkout button disable functionality added

---

public/css/responsive.css

Update responsive styles for flash sale content area

Update responsive styles for flash sale content area

---

public/css/responsive.css

Add responsive styles for dropdown content in CSS

Add responsive styles for dropdown content in CSS

---

app/components/AddToCartButton.jsx

Fix typo in AddToCartButton component label

Fix typo in AddToCartButton component label

---

app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductSummary.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeCardProductTableBody.jsx

Update PrivilegeCard components to calculate net price based on item quantities

Update PrivilegeCard components to calculate net price based on item quantities

---

app/career/page.jsx
app/components/MainNav.jsx
app/components/MobileNav.jsx
app/components/ProductSearchResult.jsx
app/components/ProductSearchResultMobile.jsx
app/components/customerDashboard/CustomerLeftSideNavbar.jsx
app/components/customerDashboard/affiliate/affiliateproducts/ResaleProductsInfo.jsx

Update CareerPage layout and enhance search functionality across navigation components

Update CareerPage layout and enhance search functionality across navigation components

---

app/affiliate-ref/[...refId]/page.jsx
app/api/auth/[...nextauth]/route.js
app/bkash-callback/page.jsx
app/cart-page/CartPageInfo.jsx
app/components/MainNav.jsx
app/components/MainSliderItems.jsx
app/components/MobileNav.jsx
app/components/customerDashboard/affiliate/affiliatemyteam/MyTeamList.jsx
app/components/customerDashboard/dashboard/AffiliatePartnerStatus.jsx
app/components/customerDashboard/finance/BankDetailsInfo.jsx
app/components/customerDashboard/finance/CompanyBankInfoLeft.jsx
app/components/customerDashboard/finance/MobileBankingModal.jsx
app/components/customerDashboard/finance/WithdrawHistoryModal.jsx
app/components/customerDashboard/settings/passwordtxnotp/ChangeTransactionOtp.jsx
app/components/thankyouSaleOnNagadhat/SaleOnNagadhatLeft.jsx
app/login/page.jsx
app/new-user/page.jsx
app/registration/page.jsx
app/services/affiliate-finance/getAffiliateFinanceAgents.js
app/services/placeorder/getBkashToken.js
app/services/postAddToCardInfo.js
app/services/privilegeCard/getPrivilegeCardWalletStatement.js
public/css/hero-banner.css

Update hero banner image styling and remove console logs across components

Update hero banner image styling and remove console logs across components

---

app/components/customerDashboard/affiliate/saleonnagadhatdetail/SaleOnNagadhatDetailInvoice.jsx
app/components/customerDashboard/affiliate/saleonnagadhatdetail/SaleOnNagadhatDetailNomini.jsx
app/components/customerDashboard/affiliate/saleonnagadhatdetail/SaleOnNagadhatDetailPay.jsx
app/components/customerDashboard/orderhistory/SaleOnNagadhatBottom.jsx
app/components/customerDashboard/orderhistory/SaleOnNagadhatInvoice.jsx
public/css/sale-on-nagadhat.css

Enhance styling and formatting in SaleOnNagadhat components for improved readability and consistency

Enhance styling and formatting in SaleOnNagadhat components for improved readability and consistency

---

app/services/affiliate-finance/getFinanceWithdrawHistoryById.js

[…thdrawHistoryById.js](chore: add a blank line for improved code readability in getFinanceWithdrawHistoryById.js)

chore: add a blank line for improved code readability in getFinanceWithdrawHistoryById.js

---

app/components/customerDashboard/privilegeDashboard/PrivilegeCardShoppingSummary.jsx
app/components/customerDashboard/privilegeDashboard/PrivilegeMainCard.jsx

fix: improve error handling and disable checkout button when cart is empty

fix: improve error handling and disable checkout button when cart is empty
